---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Shimotsuki.
--- DateTime: 23/06/2022 12:49
---

fx_version = "adamant"
game = 'gta5'

client_scripts{
    'client/*.lua'
}

server_scripts{
    'server/*.lua'
}