---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Shimotsuki.
--- DateTime: 23/06/2022 12:49
---

fx_version = "adamant"
game = 'gta5'

author = 'Team RKZ'
version = "1.0.0"

client_scripts{
    'Core/*.lua'
}

server_scripts{
    'Events/*.lua'
}