---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Shimotsuki.
--- DateTime: 23/06/2022 11:45
---

function RKZ.Base.Start(self)
    Citizen.CreateThread(function()
        while true do
            if NetworkIsSessionStarted() then
                TriggerEvent('RKZ-Base:Start')
                TriggerServerEvent('RKZ-Base:ServerStart')
                break
            end
        end
    end)
end

RKZ.Base.Start(self)

RegisterNetEvent("RKZ-Base:rkz:getObject")
AddEventHandler("RKZ-Base:rkz:getObject", function(callback)
    callback(RKZ)
    print("Called Back " ..RKZ )
end)