---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Shimotsuki.
--- DateTime: 23/06/2022 11:52
---

RegisterServerEvent("KRZ-Base:ServerStart")
AddEventHandler("KRZ-Base:ServerStart", function()
    local _src = source
    Citizen.CreateThread(function()
        local indentification = GetPlayerIdentifiers(_src)[1]
        if not indentification then
            DropPlayer(_src, "Indentifer not located")
        end
        return
    end)
end)

RegisterNetEvent('RKZ-Base:rkz:getObject')
AddEventHandler('RKZ-Base:rkz:getObject', function()
    callback(RKZ)
end)

AddEventHandler("RKZ-Base:addCommand", function(command, callback, suggestion, args)
    RKZ.Functions.addCommand(command, callback, suggestion, args)
end)

AddEventHandler("RKZ-Base:addGroupCommand", function(command, group, callback, callbackfailled, suggestion, args)
    RKZ.Functions.addGroupCommand(command, group, callback, callbackfailled, suggestion, args)
end)

RegisterServerEvent('RKZ-Base:Server:triggerServerCallback')
AddEventHandler('KRZ-Base:Server:triggerServerCallback', function(name, requestId, ...)
    local _src = source

    RKZ.Functions.TriggerServerCallback(name, requestId, _src, function()
        TriggerClientEvent('RKZ-Base:client:serverCallback', _src, requestId, ...)
    end, ...)
end)