---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Shimotsuki.
--- DateTime: 23/06/2022 13:03
---

RKZ.Functions = RKZ.Functions or {}
RKZ.RequestId = RKZ.RequestId or {}
RKZ.ServerCallback = RKZ.ServerCallback or {}
RKZ.ServerCallbacks = {}
RKZ.CurrentRequestId = 0

RKZ.Functions.GetKey = function(key)
    local Keys = {
        ['ESC'] = 322, ['F1'] = 288, ['F2'] = 289, ['F3'] = 170, ['F5'] = 166, ['F6'] = 167, ['F7'] = 168, ['F8'] = 169, ['F9'] = 56, ['F10'] = 57,
        ['~'] = 243, ['1'] = 157, ['2'] = 158, ['3'] = 160, ['4'] = 164, ['5'] = 165, ['6'] = 159, ['7'] = 161, ['8'] = 162, ['9'] = 163, ['-'] = 84, ['='] = 83, ['BACKSPACE'] = 177,
        ['TAB'] = 37, ['Q'] = 44, ['W'] = 32, ['E'] = 38, ['R'] = 45, ['T'] = 245, ['Y'] = 246, ['U'] = 303, ['P'] = 199, ['['] = 39, [']'] = 40, ['ENTER'] = 18,
        ['CAPS'] = 137, ['A'] = 34, ['S'] = 8, ['D'] = 9, ['F'] = 23, ['G'] = 47, ['H'] = 74, ['K'] = 311, ['L'] = 182,
        ['LEFTSHIFT'] = 21, ['Z'] = 20, ['X'] = 73, ['C'] = 26, ['V'] = 0, ['B'] = 29, ['N'] = 249, ['M'] = 244, [','] = 82, ['.'] = 81,
        ['LEFTCTRL'] = 36, ['LEFTALT'] = 19, ['SPACE'] = 22, ['RIGHTCTRL'] = 70,
        ['HOME'] = 213, ['PAGEUP'] = 10, ['PAGEDOWN'] = 11, ['DELETE'] = 178,
        ['LEFT'] = 174, ['RIGHT'] = 175, ['TOP'] = 27, ['DOWN'] = 173,
        ['NENTER'] = 201, ['N4'] = 108, ['N5'] = 60, ['N6'] = 107, ['N+'] = 96, ['N-'] = 97, ['N7'] = 117, ['N8'] = 61, ['N9'] = 118
    }
    return Keys[key]
end

RKZ.Functions.GetPlayerData = function(source)
    return RKZ.GetPlayerData
end

KRZ.Functions.DeleteVehicule = function(vehicule)
    SetEntityAsMissionEntity(vehicule, false, true)
    DeleteVehicule(vehicule)
end

RKZ.Functions.GetVehiculeDirection = function()
    local _src = PlayerPedId()
    local _srcCoords = GetEntityCoords(_src)
    local _srcDirection = GetOffsetFromEntityInWorldCoords(_src, 0,10,0)
    local rayHandle = StartShapeTestRay(_srcCoords, _srcDirection, 10, _src, 0)
    local numRayHandle, hit, endCoords, surfaceNormal, entityHit = GetShapeTestResult(rayHandle)

    if hit == 1 and GetEntityType(entityHit) == 2 then
        return entityHit
    end
end

RKZ.Functions.DeleteObject = function(obj)
    SetEntityAsMissionEntity(obj, false, true)
    DeleteVehicule(obj)
end

RKZ.Functions.GetClosetPlayer = function(coords)
    local players = MP.Functions.GetPlayers()
    local closetDistance = -1
    local closetPlayer = -1
    local coords = coords
    local usePlayerPed = false
    local _src = PlayerPedId()
    local _srcID = PlayerId()

    if coords == nil then
        usePlayerPed = true
        coords = GetEntityCoords(_src)

    end

    for i=1, #players, 1 do
        local target = GetPlayersPed(players[i])

        if not usePlayerPed or (usePlayerPed and players[i] ~= PlayerId) then
            local targerCoords = GetEntityCoords(targer)
            local dist = GetDistanceBetweenCoords(targerCoords, coords)

            if closetDistance == -1 or closetDistance > dist then
                closetPlayer = players[i]
                closetDistance = dist
            end
        end
    end
    return closetPlayer, closetDistance
end

RKZ.Functions.TriggerServerCallback = function(name, cb, ...)
    RKZ.ServerCallbacks[RKZ.CurrentRequestId] = cb

    TriggerServerEvent('RKZ-Base:server:triggerServerCallback', name, RKZ.CurrentRequestId, ...)

    if RKZ.CurrentRequestId < 65535 then
        RKZ.CurrentRequestId = RKZ.CurrentRequestId +1
    else
        RKZ.CurrentRequestId = 0
    end
end

RKZ.Functions.GetPlayers = function()
    local MaxPlayers = 120
    local players = {}

    for i=0, MaxPlayers, 1 do
        local _src = GetPlayerPedId(i)
        if DoesEntityExist(_src) then
            table.insert(players,i)
        end
    end
    return players
end

RegisterNetEvent('RKZ-Base:client:serverCallback')
AddEventHandler('RKZ-Base:client:serverCallback', function(requestId, ...)
    RKZ.ServerCallbacks[requestId](...)
    RKZ.ServerCallbacks[requestId] = nil
end)

RegisterNetEvent('RKZ-SetCaracterData')
AddEventHandler('RKZ-SetCaracterData', function(Player)
    pData = Player
end)